build-job:
  image: node:lts
  services:
    - mongo:latest
    - redis:latest
  cache:
    paths:
      - node_modules/
      - packages/calendar/node_modules/
  script:
   - node -v
   - npm -v
   - echo $NODE_ENV
   - node scripts/packages/build.js
   - npm install
   - npm run build
   - npm run test

deploy-heroku:
  type: deploy
  script:
    - apt-get update -qy
    - apt-get install -y ruby-dev
    - gem install dpl
    - dpl --provider=heroku --app=rollbooking --api-key=$HEROKU_ROLLBOOKING_API_KEY
  only:
    - master
